import { chromium } from 'playwright';
const FIX = '/home/claude/feuillet/tests/fixtures';
const W = Number(process.env.W || 390), H = Number(process.env.H || 844), tag = process.env.TAG || 'm';
const browser = await chromium.launch({ env: { ...process.env, LANG: 'C.UTF-8' }, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-video-capture=/tmp/claude-0/document.y4m`] });
const ctx = await browser.newContext({ viewport: { width: W, height: H }, permissions: ['camera'], colorScheme: process.env.DARK ? 'dark' : 'light' });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log(`[pageerror] ${e.message}`));
page.on('console', (m) => m.type() === 'error' && console.log(`[console] ${m.text()}`));
const shot = (n) => page.screenshot({ path: `/tmp/m/${tag}-${n}.png` });
await page.goto('http://localhost:4173/');
// scan one doc
await page.goto('http://localhost:4173/#/scan');
await page.waitForURL(/review/, { timeout: 15000 });
await page.click('[data-testid=review-validate]');
await page.waitForURL(/#\/doc\//);
await page.waitForTimeout(2500);
// import files
await page.goto('http://localhost:4173/');
const fc = page.waitForEvent('filechooser');
await page.locator('button[aria-label="Importer des fichiers"]').first().click();
await (await fc).setFiles([`${FIX}/office/sample.docx`, `${FIX}/office/releve.xlsx`, `${FIX}/office/deck.pptx`, `${FIX}/office/sample.pdf`]);
await page.waitForTimeout(4000);
await page.goto('http://localhost:4173/');
await page.waitForTimeout(800);
await shot('01-library');
await page.goto('http://localhost:4173/#/search?q=facture');
await page.waitForTimeout(800);
await shot('02-search');
await page.goto('http://localhost:4173/');
await page.locator('.doc-grid .doc-card').first().click();
await page.waitForTimeout(800);
await shot('03-doc');
await page.locator('.page-grid .page-btn').first().click();
await page.waitForTimeout(400);
await shot('04-pagemenu');
await page.getByRole('menuitem', { name: /Filtres et réglages/ }).click();
await page.waitForTimeout(1500);
await shot('05-filter');
await page.getByRole('radio', { name: 'Texte' }).click();
await page.waitForTimeout(600);
await shot('06-text');
await page.getByRole('radio', { name: 'Annoter' }).click();
await page.waitForTimeout(800);
await shot('07-annotate');
await page.getByRole("button", { name: "Retour au document" }).click();
await page.waitForTimeout(500);
await page.getByTestId('export-open').click().catch(() => {});
await page.waitForTimeout(600);
await shot('08-export');
await page.keyboard.press('Escape');
await page.goto('http://localhost:4173/#/tools');
await page.waitForTimeout(500);
await shot('09-tools');
await page.goto('http://localhost:4173/#/settings');
await page.waitForTimeout(500);
await shot('10-settings');
// open an office doc
await page.goto('http://localhost:4173/#/search?q=trimestriel');
await page.waitForTimeout(600);
await page.locator('.doc-row').first().click();
await page.waitForTimeout(800);
await shot('11-docx');
await browser.close();
